name: CI for ToDo app

run-name: ${{ github.actor }} is running workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          apt update && apt upgrade
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint code
        run: |
          flake8 ./app/core/config.py
          flake8 ./app/core/database.py
          flake8 ./app/tasks/models.py
          flake8 ./app/tasks/routes.py
          flake8 ./app/tasks/schemas.py
          flake8 ./app/main.py

